arr = [
    { "id":  1, "name": "round",     "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id":  2, "name": "roundEven", "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id":  3, "name": "trunc",     "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id":  4, "name": "abs",       "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id":  5, "name": "abs",       "forall": { "T": "genIType" }, "type": ["T", ["T"]] },
    { "id":  6, "name": "sign",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id":  7, "name": "sign",      "forall": { "T": "genIType" }, "type": ["T", ["T"]] },
    { "id":  8, "name": "floor",     "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id":  9, "name": "ceil",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 10, "name": "fract",     "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 11, "name": "radians",   "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 12, "name": "degrees",   "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 13, "name": "sin",       "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 14, "name": "cos",       "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 15, "name": "tan",       "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 16, "name": "asin",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 17, "name": "acos",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 18, "name": "atan",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 19, "name": "sinh",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 20, "name": "cosh",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 21, "name": "tanh",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 22, "name": "asinh",     "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 23, "name": "acosh",     "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 24, "name": "atanh",     "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 25, "name": "atan2",     "forall": { "T": "genType" }, "type": ["T", ["T", "T"]] },
    { "id": 26, "name": "pow",       "forall": { "T": "genType" }, "type": ["T", ["T", "T"]] },
    { "id": 27, "name": "exp",       "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 28, "name": "log",       "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 29, "name": "exp2",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 30, "name": "log2",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 31, "name": "log2",      "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 32, "name": "inversesqrt", "forall": { "T": "genType" }, "type": ["T", ["T"]] },
    { "id": 33, "name": "determinant", "forall": { "T": "genMatType" }, "type": ["float", ["T"]] },
    { "id": 34, "name": "inverse", "forall": { "T": "genMatType" }, "type": ["T", ["T"]] },
    { "id": 35, "name": "modf", "forall": { "T": "genType" }, "type": ["T", ["T", "T*"]] },

    { "id": 37, "name": "min", "forall": { "T":  "genType" }, "type": ["T", ["T", "T"]] },
    { "id": 38, "name": "min", "forall": { "T": "genUType" }, "type": ["T", ["T", "T"]] },
    { "id": 39, "name": "min", "forall": { "T": "genIType" }, "type": ["T", ["T", "T"]] },

    { "id": 40, "name": "max", "forall": { "T":  "genType" }, "type": ["T", ["T", "T"]] },
    { "id": 41, "name": "max", "forall": { "T": "genUType" }, "type": ["T", ["T", "T"]] },
    { "id": 42, "name": "max", "forall": { "T": "genIType" }, "type": ["T", ["T", "T"]] },

    { "id": 43, "name": "clamp", "forall": { "T":  "genType" }, "type": ["T", ["T", "T", "T"]] },
    { "id": 44, "name": "clamp", "forall": { "T": "genUType" }, "type": ["T", ["T", "T", "T"]] },
    { "id": 45, "name": "clamp", "forall": { "T": "genIType" }, "type": ["T", ["T", "T", "T"]] },

    { "id": 46, "name": "mix", "forall": { "T":  "genType" }, "type": ["T", ["T", "T", "T"]] },
    { "id": 48, "name": "step", "forall": { "T":  "genType" }, "type": ["T", ["T", "T"]] },
    { "id": 49, "name": "smoothstep", "forall": { "T":  "genType" }, "type": ["T", ["T", "T", "T"]] },
    { "id": 50, "name": "fma", "forall": { "T":  "genType" }, "type": ["T", ["T", "T"]] },
    { "id": 51, "name": "frexp", "forall": { "T":  "genType" }, "type": ["T", ["T", "T*"]] },
    { "id": 53, "name": "ldexp", "forall": { "T":  "genType" }, "type": ["T", ["T", "T*"]] },

]